---
config:
  wrap: true
---
classDiagram
%% Domain model
namespace domain {
%% Base entity
class Animal {
  <<abstract>>
  +String name
  #int age
  +makeSound() void
  #sleep() void
}
%% Concrete animal
class Duck {
  <<entity>>
  +String featherColor
  +swim() bool
}
class Habitat {
  +String location
}
class Pond {
  +clean() void
}
class Flyable {
  <<interface>>
  +fly() bool
}
class Bird {
  +float wingSpan
  +layEgg() int
}
}
%% Application services
namespace services {
class FeedingService {
  <<service>>
  +feed(animal: Animal) void
}
}
Animal <|-- Duck : extends
Pond "1" *-- "1" Habitat : contains
Habitat "1" o-- "*" Animal : hosts
Animal "1" -- "1" FeedingService : fed by
FeedingService <.. Duck : uses
Flyable <|.. Bird : implements
note for Animal "Abstract domain type"
note for Duck "Concrete class"
note for Pond "Composition example"
note for FeedingService "Dependency example"
note for Bird "Realization example"
